### ISSUE TITLE
Media Notification not dismissed when app is closed from Multitasking.

### ISSUE THREAD

**Issue by YaarPatandarAA** [gaucidaniel/native-audio#13]
On Android the media notification stays open as well as the Media Session. The media will continue to play and not stop when the app has closed from Multitasking. 

Additionally if the app is launched again the old media session does not hook into the new app launch. Thus causing the new app launch media to collide with the old already playing media and causing app crash.

The Media Notification, Media Session, Audio Player, and etc. should all stop and shutdown when the app is closed. As this is the case for most streaming apps on Android: Youtube Music, Apple Music on Android, Spotify, etc.

**Comment by YaarPatandarAA** [comment]
My Workaround
---------------
NativeAudioPlugin.kt

    var serviceConnection_GLOBAL: ServiceConnection? = null
    var context_GLOBAL: Context? = null
    
    context_GLOBAL = context
    serviceConnection_GLOBAL = serviceConnection


MainActivity.kt

    import android.content.Intent
    import com.danielgauci.native_audio.AudioService
    import com.danielgauci.native_audio.context_GLOBAL
    import com.danielgauci.native_audio.serviceConnection_GLOBAL
    
    override fun onDestroy() {
        super.onDestroy()
        serviceConnection_GLOBAL?.let { context_GLOBAL?.unbindService(it) }
        context_GLOBAL?.stopService(Intent(context_GLOBAL, AudioService::class.java))
        
        finishAndRemoveTask()
        exitProcess(0)
      }

**Comment by BokAugust** [comment]
> ## My Workaround
> NativeAudioPlugin.kt
> 
> ```
> var serviceConnection_GLOBAL: ServiceConnection? = null
> var context_GLOBAL: Context? = null
> 
> context_GLOBAL = context
> serviceConnection_GLOBAL = serviceConnection
> ```
> 
> MainActivity.kt
> 
> ```
> import android.content.Intent
> import com.danielgauci.native_audio.AudioService
> import com.danielgauci.native_audio.context_GLOBAL
> import com.danielgauci.native_audio.serviceConnection_GLOBAL
> 
> override fun onDestroy() {
>     super.onDestroy()
>     serviceConnection_GLOBAL?.let { context_GLOBAL?.unbindService(it) }
>     context_GLOBAL?.stopService(Intent(context_GLOBAL, AudioService::class.java))
>     
>     finishAndRemoveTask()
>     exitProcess(0)
>   }
> ```

Thanks so much , that's worked for me.

**Comment by BokAugust** [comment]
Btw , on the newest Flutter version , `exitProcess(0)` should change to 'System.exit(0)' , that will be wroking fine.

**Comment by jatorresdev** [comment]
Hola @YaarPatandarAA and @BokAugust. I'm trying to make the adjustment they suggest, but I don't know which line I should paste the code snippet into. They could guide me a little, I don't know anything about kotlin and I'm a little confused. Thanks so much.

**Comment by jatorresdev** [comment]
Hi @YaarPatandarAA and @BokAugust. I'm trying to make the adjustment they suggest, but I don't know which line I should paste the code snippet into. They could guide me a little, I don't know anything about kotlin and I'm a little confused. Thanks so much.
