### ISSUE TITLE
iOS Control Center Media does NOT show AlbumArt

### ISSUE THREAD

**Issue by YaarPatandarAA** [gaucidaniel/native-audio#2]
AlbumArt (imageURL) is not displayed in the Media Controls on iOS. The Flutter App Logo is instead displayed.

**Comment by YaarPatandarAA** [comment]
I see where it goes, the imageURL is not used. I can push the fix by tonight hopefully.

**Comment by YaarPatandarAA** [comment]
```
private func showMediaInfo(call: FlutterMethodCall, result: FlutterResult){
    let arguments = call.arguments as! NSDictionary
    let imgURL = arguments["imgURL"] as! String
    let trackTitle = arguments["trackTitle"] as! String
    let albumTitle = arguments["albumTitle"] as! String
    let artistName = arguments["artistName"] as! String
    
    let url = URL(string: imgURL)
    if let data = try? Data(contentsOf: url!)
    {
        let image: UIImage = UIImage(data: data)!
        updateNowPlayingInfoCenter(artwork: image, trackTitke: trackTitle, albumTitle: albumTitle, artistName: artistName)
        result(trackTitle)
    }
    
}

private func updateNowPlayingInfoCenter(artwork: UIImage? = nil, trackTitke: String, albumTitle: String, artistName: String) {
    MPNowPlayingInfoCenter.default().nowPlayingInfo = [
        MPMediaItemPropertyTitle: trackTitke,
        MPMediaItemPropertyAlbumTitle: albumTitle,
        MPMediaItemPropertyArtist: artistName,
    ]
    if let artwork = artwork {
        MPNowPlayingInfoCenter.default().nowPlayingInfo?[MPMediaItemPropertyArtwork] = MPMediaItemArtwork.init(boundsSize: artwork.size, requestHandler: { (size) -> UIImage in
            return artwork
        })
    }
}
```


This is how I am handling the media info on my App. See how the Image is being used.

*Note: My App uses a different Audio Player library thus why I don't have track url. This is why I prefer your library over my current implementation in my App, kills two birds with one stone.

**Comment by div3791** [comment]
is there a feature to control player by bluetooth devices??? I mean play, stop, pause etc. with notification and play in background? with this library?

**Comment by YaarPatandarAA** [comment]
All of these should already be working? @div3791

- Using Bluetooth I am able to Play, Pause, Stop, Next(Currently Skip XX Seconds), Previous(Currently Skip XX Seconds).
- Background playback also works fine on both iOS and Android. Do note on iOS when you close the App it will kill music playback, this is by default from iOS.
- Incoming calls are also handled by pausing the media playback. On android media will resume when call is ended.
- On Android media stays playing when app is closed and you can pause media then kill the media notification.

**Comment by gaucidaniel** [comment]
Thanks for the suggestions and pull requests @YaarPatandarAA, will test out the changes and release tonight.

**Comment by gaucidaniel** [comment]
@YaarPatandarAA merged most of the pull requests and released an update (also credited you in the changelog). Once again, thanks again for your initiative.
